language: node_js
node_js:
  - 8
script:
- npm run lint
- npm test
- npm run build
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: outdoormaps.eu
  on:
    branch: master
