name: Test and Deploy

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Verify
        run: |
          npm install
          npm run lint
          npm run prettier:check
          npm test
      - name: Build
        run: |
          npm run build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
          fqdn: outdoormaps.eu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
